name: v1

on:
  push: 
    branches: [master]

jobs:
  v1_0_3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "action-aws-cf-to-dotenv"
      - uses: ./
        with:
          stack-names: "foo"
          prefix: CF_
          output: .env
          format: shell

        env:
          AWS_ACCESS_KEY_ID: foo
          AWS_SECRET_ACCESS_KEY: foo
          AWS_DEFAULT_REGION: us-east-1
      - run: cat .env
     